export default {
  login: "Admiral-Simo",
  id: 109309386,
  node_id: "U_kgDOBoPtyg",
  avatar_url: "https://avatars.githubusercontent.com/u/109309386?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Admiral-Simo",
  html_url: "https://github.com/Admiral-Simo",
  followers_url: "https://api.github.com/users/Admiral-Simo/followers",
  following_url:
    "https://api.github.com/users/Admiral-Simo/following{/other_user}",
  gists_url: "https://api.github.com/users/Admiral-Simo/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Admiral-Simo/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Admiral-Simo/subscriptions",
  organizations_url: "https://api.github.com/users/Admiral-Simo/orgs",
  repos_url: "https://api.github.com/users/Admiral-Simo/repos",
  events_url: "https://api.github.com/users/Admiral-Simo/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Admiral-Simo/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2022-07-14T18:45:55Z",
  updated_at: "2023-02-03T07:41:51Z",
};
